 CLASS zsat_abap_test_class DEFINITION
  PUBLIC FINAL
  CREATE PUBLIC
  FOR TESTING.

   PUBLIC SECTION.
   PROTECTED SECTION.
   PRIVATE SECTION.
 ENDCLASS.

 CLASS zsat_abap_test_class IMPLEMENTATION.
 ENDCLASS.
